### PR TITLE
fix: handle active GitHub Actions builds

### LINKED ISSUE #54: Release Build Route Doesn't Handle GitHub Actions
Now that we've migrated from CircleIC to GitHub Actions, we need to update https://github.com/electron/release-status/blob/main/src/routes/release-build.js to handle GHA builds.

### PR DESCRIPTION
**Pull request by dsanders11**
Fixes #54.

### CODE REVIEW

File: src/routes/release-build.js [hunk 1]
```diff
@@ -50,15 +61,23 @@ router.get(
 
     const ciBuilds = [];
     if (build.ciBuilds) {
-      for (const circleBuild of build.ciBuilds.circle) {
+      for (const circleBuild of build.ciBuilds.circle ?? []) {
```
Comment (VerteDinde) [inline src/routes/release-build.js:64]: I think we can actually kill this; CircleCI should be out of all branches on e/e now

**Review by VerteDinde — APPROVED** [review]
Looks good to me with one non-blocking comment!

File: src/routes/release-build.js (hunk 1 above)
Comment (dsanders11) [reply src/routes/release-build.js:64]: Yea, it might be safe to remove all together now, but part of me wants to leave it "just in case". 😅 A future PR could clean out dead code here.
